export const fetchUserType = {
  STARTED: "FETCH_USER_STARTED",
  SUCCESS: "FETCH_USER_SUCCESS",
  TSUCCESS: "FETCH_USER_TASK",
  FAILURE: "FETCH_USER_FAILURE",
};

export const fetchMessageType = {
  STARTED: "FETCH_MESSAGE_STARTED",
  SUCCESS: "FETCH_MESSAGE_SUCCESS",
  CREATE_SUCCESS: "CREATE_MESSAGE_SUCCESS",
  FAILURE: "FETCH_MESSAGE_FAILURE",
};

export const fetchChannelType = {
  STARTED: "FETCH_CHANNEL_STARTED",
  SUCCESS: "FETCH_CHANNELS_SUCCESS",
  FETCH_SUCCESS: "FETCH_CHANNEL_SUCCESS",
  FETCH_MEMBER_SUCCESS: "FETCH_MEMBER_CHANNEL_SUCCESS",
  CREATE_SUCCESS: "CREATE_CHANNEL_SUCCESS",
  DELETE_SUCCESS: "DELETE_CHANNEL_SUCCESS",
  FAILURE: "FETCH_CHANNEL_FAILURE",
};

export const fetchCurrentChannelType = {
  STARTED: "FETCH_CURRENT_CHANNEL_STARTED",
  SUCCESS: "FETCH_CURRENT_CHANNEL_SUCCESS",
  EDIT_SUCCESS: "EDIT_CURRENT_CHANNEL_SUCCESS",
  EDIT_MEMBER_SUCCESS: "EDIT_MEMBER_CURRENT_CHANNEL_SUCCESS",
  FAILURE: "FETCH_CURRENT_CHANNEL_FAILURE",
};

export const fetchColorType = {
  STARTED: "FETCH_COLOR_STARTED",
  SUCCESS: "FETCH_COLOR_SUCCESS",
  FAILURE: "FETCH_COLOR_FAILURE",
};
